version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run: echo "Build job berhasil dijalankan"
  test:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run: echo "Test job berhasil dijalankan"

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
     - add_ssh_keys:
            fingerprints:
              - f1:92:66:bf:3b:b2:9e:04:f9:45:3d:20:2a:35:03:80
      - build
      - test
