version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run: echo "Build job berhasil dijalankan"
  test:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run: echo "Test job berhasil dijalankan"
  deploy:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run: echo "Deploy berhasil"

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test
  deploy:
    jobs:
      - deploy
